// export { default as template } from './template'
export { default as events } from './events'
export { default as notifications } from './notifications'
export { default as eventsModal } from './event_modal'
export { default as account } from './account'
